dist: precise
language: php

php:
  - 7.4

cache:
  directories:
    - vendor

before_script:
  - composer self-update
  - composer global require hirak/prestissimo
  - composer install --no-interaction

script:
  - vendor/bin/phpunit