#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\SingleCommandApplication;
use MoneyToWords\Converter;

(new SingleCommandApplication())
    ->setName('Money to words converter')
    ->setVersion('1.0.0')
    ->addArgument('number', InputArgument::REQUIRED)
    ->addOption('currency', null, InputOption::VALUE_OPTIONAL, '', 'dollars')
    ->addOption('unit', null, InputOption::VALUE_OPTIONAL, '', 'cents')
    ->setCode(function (InputInterface $input, OutputInterface $output) {
        $number = $input->getArgument('number');
        $currency = $input->getOption('currency');
        $unit = $input->getOption('unit');

        $output->writeln($number . ' => ' . Converter::convert($number, $currency, $unit));
    })
    ->run()
;